### ISSUE TITLE
Change get() to read() to match CRUD

### ISSUE THREAD

**Issue by FireDart** [tres-framework/Trestle#12]
This might seem trivial but I think we should replace the `get()` method with `read()`. Trestle is a CRUD based PDO wrapper. CRUD of course standing for **C**reate, **R**ead, **U**pdate & **D**elete. We currently use `create()`, `get()`, `update()` & `delete()` which is "CGUD".

I know the term is less important then the task but since we using the same letters/word from the acronym for the other three it might be better to go with `read()`.

```php
$data = $db->read('posts', ['id', 'title'])
           ->limit(10)
           ->exec();
```

Meaning is the same and is a easy change + makes things a bit more standard across the board which I personally like.

Opinion @pedzed?

**Comment by pedzed** [comment]
"data is equal to database get from posts: id, title; limit 10 and execute"

"data is equal to database read from posts: id, title; limit 10 and execute"

The former is easier to say and more logical than the latter. The database *gets* data; the end user *reads* information from the data.

I know I prefer `get`, but it's not a big deal to me if it would be `read`.
