### ISSUE TITLE
Better solution needed for rawBind.

### ISSUE THREAD

**Issue by FireDart** [tres-framework/Trestle#13]
With issue #10 getting a rework this issue is really starting to show it's problems.

Currently all data is wrapped with a backtick, exclusion being the third parameter of where() because it gets overwritten with binds (?, ?, ?).

This leads to a few problems
1. What if you want a raw string for the first parameter of where()
```php
SELECT * FROM `table` WHERE not_wrapped = `bind`
```
Not possible
2. $rawBind in `where()` is also used to avoid binds (?, ?, ?) and `LIKE`
```php
->where('id', '=', 1) // returns id = ?
->where('id', '=', 1, true) // returns id = `1`
->where('id', 'LIKE', 'example') // returns `id` LIKE ?
->where('id', 'LIKE', 'example', true) // returns `id LIKE `example`
```
The second is actually a bug with `Engineer::_stringWrapper` but still an issue regardless.
3. `on()` is unreliable because you can't customize it.
```php
->on('articles.author', '=', 'users.id') // Fine; returns `articles`.`author` = `users`.`id`
->on('users.id', '=', 1, true) // returns `users`.`id` = 1
->on('not_wrapped', '=', 'bind', true) // returns `not_wrapped` = bind
```
`not_wrapped` will be wrapped regardless.

Making the fourth parameter the decoding factor is power design (on my part) and will make customization hard.

The question is how do we allow customize raw strings to be inserted? I believe other PDO wrappers do something like:
```php
->where('id', '=', DB::raw('1'))
```
We are not static so our syntax would be:
```php
->where('id', '=', $db->raw('1'))
```
This would work but does it flow well, can we find a better solution?

Doing something in the syntax like
```php
->where('id', '=', 'raw:\\1')
```
Seems like a bad option and messy as well.

This is an issue that can not be solved with "Use the query method `$this->query(...)->exec()`". It's something that really changes usability.

With joins being almost finished with issue #10 this should be the last issue for V0.2, excluding a refactoring of the `where()` method.

**Comment by pedzed** [comment]
> 1. What if you want a raw string for the first parameter of where()
> 
> ```sql
SELECT * FROM `table` WHERE not_wrapped = `bind`
```
> Not possible

What's `not_wrapped` supposed to be? I don't see why one would want to do that.

I'm not entirely sure what you mean with 2 and 3, but I know that quoted identifiers (`` ` `` in MySQL) is important, because one of Trestle's goals is to support multiple drivers. Other drivers don't use backticks, so this is indeed important.

**Comment by FireDart** [comment]
> What's `not_wrapped` supposed to be? I don't see why one would want to do that.

I should have clarified, I apologize. It's less that it is logical to do but rather the user should have the option. If they can make one of the parameters un-wrapped with backticks then they should be able to do both.

As well if they had a column with a dot in the name (here we go again!) they should be able to still run the following (in theory)
```php
$query = $db->read(['articles.id', 'articles.title', $db->raw('article.date.posted'), 'users.username'])
            ->where($db->raw('article.date.posted'), '=', '2015-03-03')
            ->exec();
```
Returns
```sql
SELECT 
    `articles`.`id`, 
    `articles`.`title`, 
    article.date.posted, 
    `users`.`username` 
FROM 
    `articles`, 
    `users` 
WHERE 
    article.date.posted = ?
```
Again it's dumb to have a dot in the column name but this is an example to allow freedom while making the code usable. Another example is adding the backticks in the `$db->raw()`:
```php
$query = $db->read(['articles.id', 'articles.title', $db->raw('`article`.`date.posted`'), 'users.username'])
            ->where($db->raw('`article`.`date.posted`'), '=', '2015-03-03')
            ->exec();
```
Which would the return:
```sql
SELECT 
    `articles`.`id`, 
    `articles`.`title`, 
    `article`.`date.posted`, 
    `users`.`username` 
FROM 
    `articles`, 
    `users` 
WHERE 
    `article`.`date.posted` = ?
```

My main complaint is it is taking-up a method argument for `where()` and `on()`. It just seems pointless when we could have a cleaner solution which provides an option anywhere in the code.

I'm not 100% how this will work but I guess if it detects an object (`$db->raw()`) then it knows not to touch it? Does this seem like a good solution or do you have a better solution with less syntax and has better readability?

> I'm not entirely sure what you mean with 2 and 3, but I know that this quoted identifier problem (backticks in MySQL) is important, because other drivers don't use backticks. And one of Trestle's goals is to support multiple drivers.

In every `\Trestle\blueprint\SchemaName` (SchemaName = MySQL, etc...) you have the following at the top:
```php
/**
 * What should be wrapped around variables when using wrap methods.
 *
 * @var string
 */
protected $_varWrapper = '`';
```

You specify the value (if one exists) that should be used to wrap columns, tables, etc.., this is per blueprint. The default in `\Trestle\Engineer` is no wrapping.

That is the idea in theory, if it transfers over is the real question.

**Comment by pedzed** [comment]
> I'm not 100% how this will work but I guess if it detects an object ($db->raw()) then it knows not to touch it? Does this seem like a good solution or do you have a better solution with less syntax and has better readability?

It's alright I suppose. What about adding the option to disable it completely for the current query?

````php
->execRaw();
```

instead of 

````php
->exec();
```

?

**Comment by FireDart** [comment]
Current issue is queries are built on the fly (formatting, add backticks, etc...)  as each method is stringed, so saying at the end "keep the query raw" might be an issue because it's already all done. I would need to change it so it saves everything then creates the query at the end.

I'm thinking I will need to move to something like this (mentioned before)
```php
\Trestle\Wireframe --> \Trestle\blueprints\MySQL --> \Trestle\Engineer
 ^ Collects data        ^ Formats data                ^ Executes data
   & validates
```

I'm building it more to represent that as I keep seeing limitations of building it on the fly but will take time since it will be a semi-heavy code refactoring.

Might just release 0.2 at the current state because it's working with a good amount of features for MySQL.

As well what should be the next drive to add so I can start thinking long term #15.

**Comment by FireDart** [comment]
RawBind update, I mixed the two proposed ideas.

If I take the following syntax:
```php
$query = $db->create('users', [
                'id'          => 1337,
                'username'    => 'foobar',
                'email'       => 'foo@bar.tld',
                'password'    => 'cleartextwoot',
                'firstname'   => 'Foo',
                'lastname'    => 'Bar',
                'active'      => 0,
                'permissions' => '{\'admin\': 0}',
            ])
            ->exec();
```

`->exec()` creates the following:
```sql
INSERT INTO `users` (`id`, `username`, `email`, `password`, `firstname`, `lastname`, `active`, `permissions`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
```

While `->execRaw()` creates the following
```sql
INSERT INTO `users` (`id`, `username`, `email`, `password`, `firstname`, `lastname`, `active`, `permissions`) VALUES ('1337', 'foobar', 'foo@bar.tld', 'cleartextwoot', 'Foo', 'Bar', '0', '{\'admin\': 0}')
```

Basically no binds and escapes any code so it can be wrapped with apostrophes.

Now take the following using the new `$db->raw()`:

```php
$query = $db->update('users', [
                'last_online' => $db->raw('CURDATE()'),
            ])
            ->where('id', '=', 1337)
            ->exec();
```

Which creates the following query
```sql
UPDATE `users` SET `last_online` = CURDATE() WHERE `id` = ?
```

`$db->raw()` removes binds, wraps and executes the code as if you where dropping in it. This is great for functions like `CURDATE` but also allowing other unique syntax.

`$db->raw()` can be used anywhere `create()`, `read()`, `update()`, `delete()`, `where()`, `join()`, `on()`, etc... you get the pictures.

I squashed most of the bugs and did a few hours of testing so I *think* it's ready for prime time but as the old saying goes
> 99 little bugs in the code,
> 99 littles bugs.
> Take one down, patch it around, 
> 117 little bugs in the code.

Version 0.2 is ready I believe.
