### ISSUE TITLE
Enhance exception and log handeling in Trestle

### ISSUE THREAD

**Issue by FireDart** [tres-framework/Trestle#17]
Exception handling in the core Trestle files is less then desirable and is poorly handled, this was bad design on my part. `Trestle\Engineer` & `Trestle\blueprints\*` are done much better. Cleaning it up should not be much a challenge.

Logs on the other hand are worse then I originally assumed. The Log code could use some work but its main issue is overhead it creates. Memory usage is the same with it on or off but execution time horrific. The entire unit test saves over 300ms from disabling it. A single query tends to gain an addition 10 ~ 40ms per query call.

Writing data to a file will always cause some slow downs but this seems a bit much.

- [x] Improve exceptions
- ~~Refactor Log class~~
- ~~Improve log speed to file system~~
- [x] Removed Log

**Comment by pedzed** [comment]
I was actually planning to do the logging.

*Still waiting for https://github.com/tres-framework/Tres-logger/pull/1*

**Comment by FireDart** [comment]
Alright that sounds good, generally logging of errors, syntax, database connections, etc.. are handled via exceptions that Tres-logger captures. You don't need it but we recommend the Tres-logger package, otherwise:
```php
set_exception_handler(function($e) {
    echo '<b>' . get_class($e) . ':</b> ' . $e->getMessage();
});
```
Will do for the most part.

Now in the query() method it throws an exception if the prepare() or execute() fails, should we:
a. Throw the query failure as an exception
b. Not throw it as an exception and pass it into debug so users can use `->debug()`
c. Have an option in the config to throw or not to throw an exception and pass it into the debug anyway

C is the current method and not having exceptions on lets you use `->debug()` otherwise you can't use it.

----

The log class it also handles the execution time, I think I'll split it into a new class called `Stopwatch` that way we can still do
```php
Stopwatch::start('total');
Stopwatch::stop('total');
```
Unless you have a better idea or a better name for the class.

Finally the main issue with not packaging a logger with Trestle is the request logs which keeps track of all query request made with info like query location, query string, query time and who executed it (ip). Without packaging a logger with Trestle what should we do about that, just drop the feature?

I guess most people won't use it anyway and if they need one they can edit the code them selves?

**Comment by FireDart** [comment]
Moved execution time calculate to a new class called Stopwatch and removed Log class. Might add request logging back in the future but for the moment it is not polished enough and does not act as a major feature.
