### ISSUE TITLE
Trestle name

### ISSUE THREAD

**Issue by pedzed** [tres-framework/Trestle#23]
Would it be better that Trestle is named "trestle"? It doesn't matter either way, but "trestle" is for example easier on case-sensitivity.

This discussion should be closed before #22.

**Comment by julianrichen** [comment]
Would we change the namespace as well? I'm fine with change the repo to `tres-framework/trestle` but I think keeping the namespace as is is preferable.

``` php
// Not a fan
$db = new trestle\database('connection_name_1');

// Better imo
$db = new Trestle\Database('connection_name_1');
```

**Comment by pedzed** [comment]
In that case, it would be:

``` php
$db = new trestle\Database('connection_name_1');
```

But you're right. I didn't mean the namespace.
