### ISSUE TITLE
Get last inserted id

### ISSUE THREAD

**Issue by pedzed** [tres-framework/Trestle#27]
How can one make use of [PDO::lastInsertId](http://www.php.net/manual/en/pdo.lastinsertid.php)?

This could be useful if you just created a new record and want to get the id. Otherwise, you would have to create a new query to get it.

@julianrichen Add the `feature request` label if applicable.

**Comment by pedzed** [comment]
Relevant: #5

**Comment by julianrichen** [comment]
Will look into. Would using the method `last()` sound right? It feels kind of vague.

``` php
$query = $db->query(...);
$query->last();
```

**Comment by pedzed** [comment]
> Will look into. Would using the method last() sound right? It feels kind of vague.

Why not just `lastInsertId()`? Or `lastInsertedId()`, but that might be too hard to remember for people who are used to PDO. 

Looking up the Trestle documentation too often is definitely what we should prevent. For me personally, after looking in a documentation twice, I should remember it. Otherwise, it's usually not named/implemented well.

**Comment by julianrichen** [comment]
Commit ecbaf5ef17f5f15158462dfd32abc85b1b3efbc4 closes this.
