### ISSUE TITLE
DSN string parser needs to be more dynamic.

### ISSUE THREAD

**Issue by julianrichen** [tres-framework/Trestle#29]
Currently the dsn string is as follow for MySQL

```
mysql:host={~host};dbname={~database};{~port};{~charset};
```

However it should be brought up to standard with:

```
mysql:host={~host};dbname={~database};port={~port};charset={~charset};
```

The core issue is if one of the arguments for port, charset, etc.. are not supplied it creates a string like so:

```
mysql:host=127.0.0.1;dbname=example_db;port={~port};charset={~charset};
```

Which throws:

```
Character set '{~charset}' is not a compiled character set and is not specified in the '/usr/share/mysql/charsets/Index.xml'
```

Trestle DSN parser should be able to
- Dynamicly add prefix (ex. `port=`) to arguments.
- Dynamicly add suffix (`;`) to arguments.
- Remove unused template patterns (`{~value}`).
- Handle `unix_socket`

Think something like `{~port|port}` which would result in:

```
mysql:{~socket|unix_socket}{~host|host}{~database|dbname}{~port|port}{~charset|charset}
```

**Comment by pedzed** [comment]
What about using `UTF-8` as default charset? And for MySQL, port `3306`.

**Comment by julianrichen** [comment]
Should we change the config so the config parameters are:

``` php
'MySQL1' => [
    'driver'      => 'MySQL',
    'host'        => '127.0.0.1',
    'dbname'      => 'trestle_1',
    'port'        => '3306',
    'charset'     => 'utf8',
    'username'    => 'root',
    'password'    => '',
    'timeout'     => 5,
],
'MySQL2' => [
    'driver'      => 'MySQL',
    'unix_socket' => '/tmp/mysql.sock',
    'dbname'      => 'trestle_1',
    'username'    => 'root',
    'password'    => '',
    'timeout'     => 5,
],
```

Diff:
`database` -> `dbname`
`socket` -> `unix_socket`

That way we can slim it down to 

```
mysql:{~unix_socket}{~host}{~dbname}{~port}{~charset}
```

and the value between `{~<value>}` equals the `<value>=<config>;`. It was my original idea but I wanted to think of alternatives so the Config could could remain the same. Making it more like PDO would be a good idea IMO.

> What about using `UTF-8` as default charset? And for MySQL, port `3306`.

I would rather PDO use it's system defaults instead of our preset defaults in-case the user changes them at the system level.

**Comment by pedzed** [comment]
> > What about using UTF-8 as default charset? And for MySQL, port 3306.
> 
> I would rather PDO use it's system defaults instead of our preset defaults in-case the user changes them at the system level.

Let's be honest here. Most of people don't touch the config files (i.e. `php.ini`). Some of them even can't. Think about shared hosting.

I am more comfortable setting up safe defaults. `UTF-8` covers most people's needs and [port `3306` is a MySQL standard](https://dev.mysql.com/doc/refman/4.1/en/connecting.html#option_general_port).

Also, here is some of the [source code of PDO_MYSQL](https://github.com/php/php-src/blob/master/ext/pdo_mysql/mysql_driver.c#L549-L555):

``` c
struct pdo_data_src_parser vars[] = {
    { "charset",  NULL, 0 },
    { "dbname",   "",   0 },
    { "host",   "localhost",    0 },
    { "port",   "3306", 0 },
    { "unix_socket",  PDO_DEFAULT_MYSQL_UNIX_ADDR,  0 },
};
```

Now tell me what "NULL" represents... It's not in the PHP documentation and you have to dig in the source code to find it.

**Comment by julianrichen** [comment]
I would be fine setting defaults but where should we store defaults? ATM we have the default arguments in the `/src/Trestle/Config.php` as:

``` php
/**
 * Mandatory parameters for each connection.
 *
 * @var private
 */
private static $_requiredArguments = [
    'MySQL' => [
        'driver',
        'database',
        'host',
        'username',
        'password'
    ],
    'SQLite' => [
        'driver',
        'database'
    ],
];
```

This is 
a. Not scalable
b. Not really designed for the issue I originally addressed

I propose we create `/src/Trestle/dsn/MySQL.php` and `/src/Trestle/dsn/SQLite.php` which will
1. Provide defaults
2. Provide possible options for a valid connection (what the $_requiredArguments does poorly, see below for example)
3. Creates the DSN dynamically with custom prefix & suffix.

Example:

``` php
<?php
return [
    'defaults' => [
        'host'      => '127.0.0.1',
        'port'      => 3306,
        'charset'   => 'utf8',
    ],
    'required' => [
        // Option 1
        [
            'driver',
            'host',
        ],
        // Option 2
        [
            'driver',
            'socket',
        ],
    ],
    'dsn' => [
        'driver'   => [
            'prefix' => '',
            'value'  => 'mysql',
            'suffix' => ':',
        ],
        'socket'   => [
            'prefix' => 'unix_socket=',
            'suffix' => ';',
        ],
        'host'     => [
            'prefix' => 'host=',
            'suffix' => ';',
        ],
        'database' => [
            'prefix' => 'dbname=',
            'suffix' => ';',
        ],
        'port'     => [
            'prefix' => 'port=',
            'suffix' => ';',
        ],
        'charset'  => [
            'prefix' => 'charset=,',
            'suffix' => ';'
        ],
    ],
];
```

We can then keep adding config files for other db types without changing Config.php, should allow for more options in the future and won't need to touch the current way configs are provided.

I'll start working on a commit to see if it might be an issue.
