### ISSUE TITLE
JOINs: aliasing enhancement

### ISSUE THREAD

**Issue by pedzed** [tres-framework/trestle#4]
First of all, I want to say that you did a great job @julianrichen. You managed to do the joining quite nicely.

There is one (small?) problem with aliasing though. I would expect the following to work:
```php
$tables = [
    'ucms_content',
    'ucms_languages'
];

$fields = [
    'ucms_content.id',
    'ucms_content.alias',
    // ...
    'ucms_languages.name' => 'language_name' // <-- this
];

$content = $static->_db->get($tables, $fields)
                       ->where('ucms_content.language_id', '=', 'ucms_languages.id', true)
                       ->exec();
```

However, that is unfortunately not possible. This is a workaround:
```php
$tables = [
    'ucms_content',
    'ucms_languages'
];

$fields = [
    'ucms_content.id',
    'ucms_content.alias',
    // ...
    'ucms_languages.name AS language_name' // <-- this
];

$content = $static->_db->get($tables, $fields)
                       ->where('ucms_content.language_id', '=', 'ucms_languages.id', true)
                       ->exec();
```
It would be great if you could improve that.

Also note that this might be a problem with issue #3.

**Edit:** This has more to do with aliasing in general I believe.

**Comment by FireDart** [comment]
I remember this being a bit difficult to implement as I had to write a couple of methods and pushed it off later as a future feature. Will look into.

**Comment by FireDart** [comment]
@pedzed Maybe you have an idea on how to handle this, if you have this:
```php
$users = $db->get(['posts' => 'p', 'users', 0 => 'example'])
            ->exec();
```
The result "should" look like so:
```
array (size=2)
  'posts' => string 'p' (length=1)
  0 => string 'users' (length=5)
  "0" => string 'example' (length=7)
```
But obviously it won't because that is not how PHP handles arrays, instead it overrides the user key:
```
array (size=2)
  'posts' => string 'p' (length=1)
  0 => string 'example' (length=7)
```
2 Problems...
1. Tables/Columns can begin with digits and can even be all digits as long as they are wrapped with back ticks
2. How do you tell the difference between the generated array key and user supplied?

If I parse:
```php
$users = $db->get(['posts' => 'p', 'users'])
            ->exec();

// Would get:
`posts` AS `p`, `0` as `users`

// Should get
`posts` AS `p`, `users`
```

A solution would to see if the key is only numeric and assume php generated it but since mysql does allow numeric I can't >:(

Ideas?

**Comment by pedzed** [comment]
> How do you tell the difference between the generated array key and user supplied?

The first thing what comes in my mind is using deeper nested arrays. Sure, this isn't optimal, but it should work:
```php
$arr = [
    [
        'key' => 'a_key',
        'value' => 'a_value'
    ],
    [
        'key' => 'a_key',
        'value' => 'a_value'
    ],
    // ...
];
```

**Comment by pedzed** [comment]
> How do you tell the difference between the generated array key and user supplied?

It's cool and all to support everything SQL allows, but ask yourself: how many people use numeric database names, tables and/or columns?

Maybe one out of a million developers would have such a weird name. I wouldn't care about them. Not necessarily because they're a minority, but because they are using such a weird convention. If they can't do anything about it, then that's too bad.

Their alternative is to use `query()`.

**Comment by FireDart** [comment]
I might just check to see if the value is numeric and if so assume it is not aliasing. I kept playing around with different idea but nothing really works well without making a ton of extra code or formatting.

I want the syntax to be as open and flexible as possible but even looking into other frameworks and the way they handle it shows they don't bother. I might not have a choice :(
