### ISSUE TITLE
order() doesn't work.

### ISSUE THREAD

**Issue by pedzed** [tres-framework/Trestle#7]
`order()` doesn't work. By using the `debug()` method, I see that the SQL statement ends with `ORDER BY ? ASC`
The problem is that you can't bind field names.

Also, issue #3 is also slightly relevant here.

**Comment by FireDart** [comment]
Can you post the code you are using? The field name(s) to be binded is the first parameter.
```php
...
    ->order('date', 'ASC')
...
```

**Comment by pedzed** [comment]
> Can you post the code you are using? The field name(s) to be binded is the first parameter.
> 
> ```php
->order('date', 'ASC')
```

I know, but you can't bind field names. You can only bind values.
```php
$sql = 'SELECT `x` FROM `y` WHERE '.$z.' = :a ORDER BY '.$b.' ASC';
```

**Comment by FireDart** [comment]
Commit 84f8cd246053fd6c6e6c7dc17cbc6ed1330f638b fixes the issue.
