### ISSUE TITLE
Unit testing for Version 0.2

### ISSUE THREAD

**Issue by FireDart** [tres-framework/Trestle#8]
We need an automatic way to test if query return the proper results.

Goal
- [x] Build a script that runs generic queries and references the expected results.
- [x] Should be stored under `/tests/`.
- [x] Returns the results as either **Passed** or **Failed** under `/tests/index.php`.
- [x] New directory called `/examples/`, which provides code examples, which is the current objective `/tests/` but under a better name.

**Comment by FireDart** [comment]
Added `/examples/` directory with commit a0d6240d245def66e05c74a862dd1e7bf4028a9e

**Comment by pedzed** [comment]
Alright, what do you have in mind? [PHPUnit](https://github.com/sebastianbergmann/phpunit)?

**Comment by FireDart** [comment]
Not 100% sure yet, I never had the need for unit testing before so this is going to be interesting.

Better to get it done now and simplify further testing then struggle to integrate later.

**Comment by pedzed** [comment]
How is it going so far? Do you have some rules for unit tests yet?

**Comment by FireDart** [comment]
`/tests/` has most of the testing: query, create, get, update, delete and tests where, limit, offset, join, on, etc...

So far I have testing if the queries are properly created by matching the debug output query (`$query->debug()['query']`) with a predefined query.

I don't have it validating the data but it should not matter if the query is properly created every time.

What's nice with phpunit is I can monitor speed as well. Once the main Trestle syntax is created I can start playing around with performance.
