### ISSUE TITLE
When using join() all columns should be in master method [get()]

### ISSUE THREAD

**Issue by FireDart** [tres-framework/Trestle#9]
As of commit 419675e25e9e82c0f2def77cd87f315f819b6b97, which fixs issue #3, you can not do the following without throwing an error:
```php
$users = $db->get('posts', ['posts.id', 'posts.title', 'users.username'])
            ->join('users')
            ->on('posts.author', '=', 'users.id')
            ->exec();
```  
Instead you must do:
```php        
$users = $db->get('posts', ['posts.id', 'posts.title'])
            ->join('users', ['users.username'])
            ->on('posts.author', '=', 'users.id')
            ->exec();
```

This is because the method `_stringWrapper()` checks for currently valid tables, if you search for the column `users.username` before including the table `users` with `join()` it fails.

Two options:
1. Don't fix, call it a "feature"
2. Create an outer class around `\Trestle\blueprints\MySQL` that collects all the information then passes it into `\Trestle\blueprints\MySQL`.

Option 2 proposal:

```php
\Trestle\Wireframe --> \Trestle\blueprints\MySQL --> \Trestle\Engineer
 ^ Collects data        ^ Formats data                ^ Executes data
   & validates
```

This needs more thought put into it so total code amount stays low. Trying to keep this as small as possible. This might also reduce total code when other database schemas are introduced.

**Comment by pedzed** [comment]
What I personally like to do is create an array with all the fields.

````php
$fields = [
    'users.id',
    'users.username',
    'articles.title',
    'article.body'
];
```

That would mean that I would have to split it in multiple arrays, which is not preferable.

If you want to do that anyway, can't you drop "`TABLE_NAME.`" and let Trestle handle it?

**Comment by FireDart** [comment]
This would be awesome and what I would also prefer:
```php
$users = $db->get(['users.id', 'users.username', 'articles.title', 'article.body'])
            ....
            ->exec();
```

But what if the column name is `users.id`, even as dumb as it is to have a dot in the column name....

As much as I don't want to do it, it might be better to just forget compensating for it and say if you use a dot in the column name just use the raw `query()` method.

If we did the above it would also slim down join() code to:

```php
$users = $db->get(['users.id', 'users.username', 'articles.title', 'article.body'])
            ->join('articles.author', '=', 'users.id')
            ->exec();
```

Since we could parse it by splinting the dot and load the **users** and **articles** just by the column name. If we don't do joins you could also do the following since it does not detect a dot.
```php
$users = $db->get('users', ['id', 'username'])
            ->exec();
```

What are your opinions on taking this stance @pedzed, talking about parsing tables using the dot and forcing users to user `query()` if it has it?

**Comment by pedzed** [comment]
> If we did the above it would also slim down join() code to:
> 
> ```php
$users = $db->get(['users.id', 'users.username', 'articles.title', 'article.body'])
            ->join('articles.author', '=', 'users.id')
            ->exec();
```
> Since we could parse it by splinting the dot and load the users and articles just by the column name. If we don't do joins you could also do the following since it does not detect a dot.
> 
> ```php
// Can still do this:
$users = $db->get('users', ['id', 'username'])
            ->exec();
// This still works:
$users = $db->get(['users.id', 'users.username'])
            ->exec();
```

Yes, they both look good to me. Remember that it can't be perfect. If it is clearly understandable, easy to type and easy to remember it's good to me. Your examples just accomplish that.

I'm more worried about other type of joins. It would be great if `INNER JOIN`, `LEFT JOIN` and `RIGHT JOIN` worked. I don't expect to see other joins as it could get really complex, but thinking about a possibility in the future would prevent backward compatibility issues.
